--- Makefile
+++ Makefile
@@ -1,10 +1,10 @@
 # Determine TEXMFROOT value by the system
-TEXLIVEDIR = /usr/share/texmf-texlive
-TEXLIVE := $(shell if [ -d ${TEXLIVEDIR} ]; then echo 1; else echo 0; fi)
+#TEXLIVEDIR = /usr/share/texmf-texlive
+#TEXLIVE := $(shell if [ -d ${TEXLIVEDIR} ]; then echo 1; else echo 0; fi)
 TEXMFROOT = /usr/share/texmf
-ifeq ($(TEXLIVE),1)
-  TEXMFROOT = $(TEXLIVEDIR)
-endif
+#ifeq ($(TEXLIVE),1)
+#  TEXMFROOT = $(TEXLIVEDIR)
+#endif
 
 
 TEXMFDIR=$(DESTDIR)$(TEXMFROOT)
@@ -14,6 +14,7 @@
 	updmap-sys --enable Map=culmus.map
 
 pkginstall:
+	if [ ! -d ${TEXMFDIR} ]; then mkdir -p ${TEXMFDIR}; fi
 	cp -vR usr/share/texmf/* ${TEXMFDIR}
 	touch $@.DONE
 
